### ISSUE TITLE
Possible to pass node or relationship label into Graph.query() function?

### ISSUE THREAD

**Issue by larryjang** [bretcope/neo4j-js#26]
@bretcope Are the following queries possible when using this node module?
`var query = 'MATCH user:{userLabel} {id: {uid}} RETURN user'`
`var query = 'MATCH user:{userLabel} {id: {uid}}-[rel:{relationshipLabel} {is_old: true}]-(system:System {id: {sysId}}) RETURN user, system'`

**Comment by bretcope** [comment]
This library hasn't been updated or supported for years. I just added a deprecation notice to the README to make that more obvious. You should choose a different Neo4j library, sorry.
